textures = ["blue-veined",
            "semi-soft",
            "washed-rind",
            "bloomy-rind",
            "runny",
            "semi-hard",
            "hard",
            "stinky",
            "double-creme",
            "triple-creme",
            "fresh",
            "moist",
            "brittle",
            "buttery",
            "chalky",
            "chewy",
            "compact",
            "crumbly",
            "dense",
            "dry",
            "elastic",
            "flaky",
            "fluffy",
            "grainy",
            "oily",
            "smooth",
            "stringy",
            "supple",
            "aged",]

cheese_names = ["swiss",
                "gouda",
                "cheddar",
                "feta",
                "mish",
                "cheese curds",
                "colby",
                "provolone",
                "brie",]

places = ["Waterdeep",
          "Neverwinter",
          "Baldur's Gate",
          "Athkatla",
          "City of Brass",
          "Everlund",
          "Luskan",
          "Suzail",
          "Lushpool",]

races = ["Tiefling",
         "Elvish",
         "Drow",
         "Kenku",
         "Orcish",
         "Half-Orc",
         "Dragonborn",
         "Half-elf",
         "Dwarven",
         "Gnomish",
         "Halfling",]


